
spring:
  application:
    name: invoice-service
  profiles:
  - dev
server:
  port: 6565
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
          

---

spring:
  application:
    name: invoice-service
  profiles:
  - prod
server:
  port: 6969
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
